# -*- coding: utf-8 -*-
"""Custom_NER.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PlgeaDPpAPRn0R7Eq_M8_fT5IEF_ayVY
"""

import spacy
from spacy import displacy
nlp = spacy.load('en_core_web_sm')
import matplotlib.pyplot as plt

with open('/content/criminal-_K.-M.-NANAVATI-VS.-STATE-OF-MAHARASHTRA_.txt','r')as file:
  text=file.read().replace('\n', '')

nlp.pipe_names

doc = nlp(text)

displacy.render(doc, style="ent", jupyter=True)

for ent in doc.ents:
  print(ent.text,ent.label_)

#after getting the entities we can form knowledge graph manually in Neo4j